# GitHub Pages Configuration
title: Leap API Documentation
description: Complete API documentation for Leap platform
baseurl: "/swagger-test"
url: "https://your-username.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude files from processing
exclude:
  - README.md
  - .gitignore
  - .github/

# Include files
include:
  - _redirects

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  api:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "api"
    values:
      layout: "api"
